// app/terms/page.tsx (or pages/terms.tsx)

"use client"

import { useRouter } from 'next/navigation'
import React from "react"

export default function TermsPage() {
    const router = useRouter()

  const handleClose = () => {
    if (typeof window !== 'undefined') {
      if (window.history.length > 1) {
        router.back()
      } else {
        router.replace('/') // fallback to homepage
      }
    }
  }

  return (
    <main className="max-w-4xl mx-auto px-6 py-12 text-white-800">
         <button
      onClick={handleClose}
      className="absolute top-5 right-5 text-white-500 hover:text-red-500 transition-colors text-2xl"
      aria-label="Close Terms and Conditions"
    >
      &times;
    </button>
      <h1 className="text-3xl font-bold mb-6">Terms and Conditions</h1>

      <p className="mb-4">
        This Terms and Conditions (“Terms”) is an electronic record in terms of the Information Technology Act, 2000 and rules made thereunder. This electronic record is generated by a computer system and does not require any physical or digital signatures.
      </p>

      <p className="mb-4">
        These Terms apply to the use of the website <a href="https://www.saaviksolutions.com" className="text-blue-600 underline">www.saaviksolutions.com</a>, its mobile-optimized version, and all related digital media formats (collectively referred to as the “Website”), owned and operated by <strong>Saavik Solutions Pvt. Ltd.</strong> (hereinafter referred to as “Company”, “We”, “Us”, or “Our”).
      </p>

      <p className="mb-4">
        Please read these Terms carefully. By accessing, browsing, or using the Website or any part of its content and Services, You (“You”, “User”, “Your”, “Yourself”, “Customer”) agree to be bound by these Terms.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-2">1. Eligibility</h2>
      <ul className="list-disc pl-6 space-y-2">
        <li>Use of the Website is permitted only to individuals who are legally capable of entering into binding contracts under the Indian Contract Act, 1872.</li>
        <li>Persons under the age of 18 may use the Website only through a parent or legal guardian.</li>
        <li>Users outside India are responsible for compliance with their local laws.</li>
        <li>If You are using the Website on behalf of a business entity or organization, You represent and warrant that You have the authority to bind that entity to these Terms.</li>
      </ul>

      <h2 className="text-xl font-semibold mt-8 mb-2">2. Acceptance of Terms</h2>
<ul className="list-disc pl-6 space-y-2">
  <li>By using this Website, You acknowledge that You have read and understood these Terms and agree to be legally bound by them.</li>
  <li>These Terms constitute a binding agreement between You and Saavik Solutions Pvt. Ltd.</li>
  <li>You agree to indemnify the Company against any breach of these Terms by You.</li>
</ul>

<h2 className="text-xl font-semibold mt-8 mb-2">3. Informational Nature</h2>
<ul className="list-disc pl-6 space-y-2">
  <li>The Website provides general information about the Company and its Services. This content is provided for informational purposes only and should not be relied upon without independent verification.</li>
  <li>The Company does not guarantee the accuracy or completeness of any content and is not liable for any reliance placed on the Website by You.</li>
</ul>

<h2 className="text-xl font-semibold mt-8 mb-2">4. Third-Party Content</h2>
<ul className="list-disc pl-6 space-y-2">
  <li>The Website may include links to third-party websites and services. These are provided for convenience only.</li>
  <li>We do not endorse or accept responsibility for any third-party materials or websites.</li>
  <li>You acknowledge that reliance on such materials is at Your own risk.</li>
</ul>

<h2 className="text-xl font-semibold mt-8 mb-2">5. Personal Information</h2>
<ul className="list-disc pl-6 space-y-2">
  <li>Your use of the Website is subject to our <a href="https://www.saaviksolutions.com/privacy-policy" target="_blank" className="text-blue-600 underline">Privacy Policy</a>.</li>
  <li>If You do not wish to have Your data used in the manner described, please do not use the Website or provide personal information.</li>
</ul>

<h2 className="text-xl font-semibold mt-8 mb-2">6. Force Majeure</h2>
<ul className="list-disc pl-6 space-y-2">
  <li>The Company shall not be liable for any failure or delay in performance due to events beyond its control, including but not limited to acts of God, war, pandemics, system failures, or government restrictions.</li>
  <li>Any such Force Majeure Event shall be determined solely by the Company.</li>
</ul>

<h2 className="text-xl font-semibold mt-8 mb-2">7. Intellectual Property</h2>
<ul className="list-disc pl-6 space-y-2">
  <li>All content on the Website, including logos, trademarks, text, graphics, software, and service names, is the intellectual property of the Company or its licensors.</li>
  <li>You may use the Website content solely for personal and non-commercial purposes.</li>
  <li>You shall not:
    <ul className="list-disc pl-6 mt-2 space-y-1">
      <li>Reverse engineer, copy, or modify any part of the Website</li>
      <li>Reproduce or distribute Website content without written permission</li>
      <li>Use the Website for unlawful or harmful purposes</li>
      <li>Engage in any data scraping, mining, or automated access</li>
    </ul>
  </li>
  <li>Any unauthorized use may result in legal action.</li>
</ul>

<h2 className="text-xl font-semibold mt-8 mb-2">8. Disclaimers and Limitation of Liability</h2>
<ul className="list-disc pl-6 space-y-2">
  <li>The Website and all content are provided on an “as-is” and “as-available” basis.</li>
  <li>We do not make warranties about the accuracy, reliability, or suitability of any information provided.</li>
  <li>The Company is not liable for any direct, indirect, incidental, or consequential damages resulting from use of the Website or Services.</li>
  <li>You acknowledge and agree that any communication from the Company (email/SMS/phone) does not violate spam or unsolicited communication laws.</li>
</ul>

<h2 className="text-xl font-semibold mt-8 mb-2">9. Indemnification</h2>
<p className="mb-4">
  You agree to indemnify and hold harmless the Company, its affiliates, officers, and employees from any claims, damages, or legal actions arising from Your use of the Website or breach of these Terms.
</p>

<h2 className="text-xl font-semibold mt-8 mb-2">10. Assignment</h2>
<p className="mb-4">
  The Company may assign its rights and obligations under these Terms without prior notice. You may not assign Your rights under these Terms without the prior written consent of the Company.
</p>

<h2 className="text-xl font-semibold mt-8 mb-2">11. Waiver</h2>
<p className="mb-4">
  Any failure or delay by the Company to enforce any provision of these Terms shall not be deemed a waiver of its rights to enforce them later.
</p>

<h2 className="text-xl font-semibold mt-8 mb-2">12. Severability</h2>
<p className="mb-4">
  If any provision of these Terms is held to be invalid or unenforceable, the remaining provisions shall remain valid and enforceable to the fullest extent permitted by law.
</p>

<h2 className="text-xl font-semibold mt-8 mb-2">13. Governing Law and Jurisdiction</h2>
<p className="mb-4">
  These Terms are governed by the laws of India. In case of any disputes, the courts in <strong>Hyderabad, Telangana</strong> shall have exclusive jurisdiction. Disputes shall be resolved through binding arbitration under the Arbitration and Conciliation Act, 1996, with the seat and venue of arbitration in Hyderabad, Telangana.
</p>


<h2 className="text-xl font-semibold mt-8 mb-2">14. Contact Us</h2>
<p className="mb-4">
  If You have any questions or concerns about these Terms, You may contact us at:
</p>
<p className="mb-1 font-medium">Saavik Solutions Pvt. Ltd.</p>
<p className="mb-1">16-2-701/d/2, Palton, Dayanand Nagar, Malakpet,</p>
<p className="mb-1">Hyderabad, Telangana – 500036</p>
<p className="mb-4">📧 Email: <a href="mailto:info@saaviksolutions.com" className="text-blue-600 underline">info@saaviksolutions.com</a></p>

    </main>
  )
}
